### PR TITLE
Update the flash tech with the final flash updates from vjs5

### PR DESCRIPTION
**Pull request by BrandonOCasey**

### CODE REVIEW

**Comment by gkatsev** [comment]
@BrandonOCasey looks like tests are failing?

**Comment by BrandonOCasey** [comment]
ahh this is because we need to update package.json when videojs 6.0.0 is out, as Dom is not currently exposed.

**Comment by gkatsev** [comment]
What about updating it to point to the RC for now?

**Comment by BrandonOCasey** [comment]
@gkatsev updated, I think the tests should pass now

**Comment by gkatsev** [comment]
I think we can merge this, though, I guess we shouldn't publish it as official until 6.0 is out of RC.

**Comment by gkatsev** [comment]
I added a note to the 6.0 project in vjs.

**Comment by gkatsev** [comment]
Actually, can we publish this as an RC as well? That way, we can add it in as a devDep to videojs to that we can include it in the sandbox if we need testing on IE8.

**Comment by BrandonOCasey** [comment]
Yeah I think that's a great idea

**Pull request merged**
